### ISSUE TITLE
command line arguments

### ISSUE THREAD

**Issue by RYG81** [gkv311/sview#10]
Hi,
Are there any commandline arguments available in sview which can be used to manage sview player from other applications?

**Comment by gkv311** [comment]
Option "--help" prints the list of known arguments:
~~~
sView --help
sView 15.08 x86_64 [build 2015-08-29]
Copyright (C) 2007-2015 Kirill Gavrilov (kirill@sview.ru).
Usage: sView [options] - file
Available options:
  --fullscreen         Open fullscreen
  --slideshow          Start slideshow
  --last               Open last file
  --paused             Open file in paused state
  --in=image,video     Application to open (predefined values: image, video, diag, cad)
  --out=RENDERER       Stereoscopic output module (auto, StOutAnaglyph, StOutDual,...)
  --imageLib=IMGLIB    Setup 3rd-party library for image processing (FFmpeg, FreeImage, DevIL)
  --viewMode=MODE      View mode (flat, sphere)
  --srcFormat=FORMAT   Setup source format:
                       auto, mono, parallelPair, crossEyed,
                       overUnderLR, overUnderRL, interlaceRow, frameSequential
  --left=PATH          Specify source for left view
  --right=PATH         Specify source for right view
~~~
this output omits some extra options not usually interesting for users.

Since sView does not implements any inter-process communication interface, there no options which would affect already running sView instances. Though video player can start simple WebUI http service which can be used to control playback from browser or another application.

**Comment by RYG81** [comment]
Actually I was looking for something like this-
http://www.3dtv.at/Products/Player/CmdLineParams_en.aspx
Is it possible for you to have these type of feature?

**Comment by gkv311** [comment]
> Is it possible for you to have these type of feature?

You have provided link to entire command line parameters list of another program.

What kind of feature you are looking for?
You are asking about similar web-page describing sView options, or you are missing some specific option?

**Comment by RYG81** [comment]
I want to launch a video without GUI in full screen with controller, with settings for file URL and input and out put format and viewing settings.
If all these command line options available in sView then a better documented page will do best. If these things are missing then want to have these if possible.

**Comment by gkv311** [comment]
> I want to launch a video without GUI in full screen with controller,

what kind of controller?

**Comment by RYG81** [comment]
With controller I mean a standard video control that we use to jump in video. like play/pause, stop button then slider and time display.

**Comment by gkv311** [comment]
> I want to launch a video without GUI 
...
> With controller I mean a standard video control that we use to jump in video.
> like play/pause, stop button then slider and time display.

these controls are part of GUI, so if you are looking for option to show some controls and hide another - this would require customization of user interface, and there no such option for video player.

Other options (fullscreen, file URL, source format, output device) already exist - see my earlier reply.

**Comment by RYG81** [comment]
but in that I do not find a proper sequence in which I should write argument.
if you can put a proper argument for opening a Top-Bottom squeezed video URL in full screen mode with viewing method of Quad buffer OpenGL 3d.

**Comment by gkv311** [comment]
~~~
sView --fullscreen --srcFormat=overUnderLR --out=StOutPageFlip -- "filePath.mkv"
~~~
Note that StOutPageFlip supports several devices (e.g. OpenGL QuadBuffer and Direct3D QuadBuffer on Windows) - the first available is automatically used and can be changed in menu (or in sView settings files / registry).

The option --outDevice has been planned to specify device within output by index, however it has not been implemented since usually there no reason to override user settings.

**Comment by RYG81** [comment]
The option --outDevice has been planned to specify device within output by index, however it has not been implemented since usually there no reason to override user settings.
is this for selecting on specific display screen in case of multiple display setup?

**Comment by RYG81** [comment]
I tested it with my videos and here are few observations-
- when loading content from URL at start the video plays slow and jerky
- if possible like to have option to hide the top interface in full screen mode by command line argument or some other possible option
- need option to exit video on double click as sometime in the dark environment it is hard to find esc or q keys on keyboard. A mouse becomes very hand in such cases.
Also have this question- How to use Web UI:8080, do you have active-X that can be directly integrated in WPF application?

**Comment by gkv311** [comment]
> is this for selecting on specific display screen in case of multiple display setup?

no, the option --outDevice has another meaning, though it is meaningless since it is not implemented anyway ;). And there no option to specify monitor from command line.

> when loading content from URL at start the video plays slow and jerky

Several reasons can cause slow/jerky playback:
- sView performs cold start - playback is started as soon as first frame has been decoded. Application uses 16 frames cache to provide smooth playback, however depending on computer performance filling this cache can take noticeable time or do not happen at all if file is too heavy for computer.
- Badly interleaved files show noticeable slowdown during opening / seeking. Audio and video frames within such files occur in the order inefficient for smooth decoding or have significant timestamps mismatch. Though technically these problems can be workarounded in some way or related demuxer in FFmpeg can be improved. Note that remuxing such files using FFmpeg, even without re-encoding might significantly improve playback!

> need option to exit video on double click as sometime in the dark environment it is hard to find esc or q keys on keyboard. A mouse becomes very hand in such cases

the fullscreen mode can be switched by middle mouse click, and since most computers have it (save the notebooks / macbooks), adding one more option does not look very reasonable.

> do you have active-X that can be directly integrated in WPF application?

there is Active-X control for image viewer, but for a different purpose - embedding into web-pages using Internet Explorer. I have no idea how ActiveX can be used within WPF applications.
Anyway, WPF can not be used as efficient application framework for stereoscopic viewer due to missing OpenGL support (only Direct3D can be embedded into WPF-based interface using D3DImage workaround) and design limitations.

> How to use Web UI:8080

Turn on Web UI in application settings, open browser and enter http://localhost/8080
For using from external application you need to use some sockets API and learn simple AJAX control queries implemented by sView (can be trivially extracted from html page).

**Comment by gkv311** [comment]
The following arguments have been added:
--toShowMenu=off to show/hide main menu
--toShowTopbar=off to show/hide top toolbar
--monitorId=ID to create window on display with specified id
--windowLeft=LEFT --windowTop=TOP --windowWidth=WIDTH --windowHeight=HEIGHT to create window with specified position

--webuiCmdPort=PORT to start extended command interface on http://localhost:PORT
--invokeAction=ACTION to invoke action in existing media player instance (on port specified by --webuiCmdPort=PORT) with following action aliases:
* play - play/pause
* mute - mute/unmute audio
* vol?VOLUME - specify volume in percents
* prev,next - play previous/next item in playlist
* fastbwd,fastfwd - seek backward/forward
* quit - close the program
* current?title - print title of currently played item
* fullscreen - switch fullscreen/windowed.

All actions having name (starting with Do__) and listed in Hot-keys dialog can be invoked within this interface.

**Comment by RYG81** [comment]
Thank you very much. Can you suggest something for streaming stereo video performance related issue?

**Comment by gkv311** [comment]
> Can you suggest something for streaming stereo video performance related issue?

For now I can recommend only trying to remux video and use MKV format.
