### ISSUE TITLE
Cubemap z axis inverted

### ISSUE THREAD

**Issue by masmil1988** [gkv311/sview#23]
I've downloaded this video:
https://www.youtube.com/watch?v=SF-3mToxpV8

It's all ok when using it with the equirectangular format. I converted it into a cubemap with this [Facebook tool](https://github.com/facebook/transform360). When seeing it with sView's cubemap I it seems to be reverted on the z-axis: http://oi67.tinypic.com/11sntbs.jpg

**Comment by gkv311** [comment]
The reversion has been done for displaying correctly images from this gallery (with cubemaps packed 6x1) - have no idea why they are flipped there:
https://render.otoy.com/vr_gallery.php

I have changed the behavior so that video player does not flip Z and image viewer flips Z only for cubemaps in 6x1 format, but not for 3x2 (configurable through application settings).
