### ISSUE TITLE
vis: anti aliasing not good

### ISSUE THREAD

**Issue by freewee** [gkv311/sview#40]
Hi, thank you for your great job!
I use sView in Windows and Ubuntu, with nVidia glasses or on my LG passive TV.
I realise something is not as good as it could be(?), in Windows and Ubuntu it is the same:
When looking my pictures on the TV, Row Interlaced, the pictures seem granulous, smoothfilter on "linear" doesn' t give a good antialiasing, and it is worst with "nearest"option.
I said it is not good as it could be, because I work my stereo pictures with Stereophoto Maker, and it is possible to look the picture in row interlaced with this soft, and the result is really better.
I send a copy of desktop, from the same picture in the 2 softs, looking at 100% shows the difference.
Is there something to adjust in sView for a best result???
Thank you!
![clipboard 4](https://user-images.githubusercontent.com/19634222/49753664-61cdf300-fcb4-11e8-9ac4-78e7a5982c04.png)

**Comment by gkv311** [comment]
Smooth filter is a texture lookup filter on graphics hardware, with Linear performing smoothing (interpolating nearest values) and Nearest useful only for seeing pixels of an image.

When image is displayed at its original resolution, so that the image pixels match screen pixels, the active filter has no effect. Filter becomes visible when image is scaled in our out (note though sView fits image into window by default, and there is no option to show image at 100% resolution).

Linear interpolation is good enough in most cases, especially when scale factor is not too big.
However, in when image resolution is much higher than screen resolution, some images might look awkward due to lost intermediate details (but the actual visual effect depends on image nature).

For that, bicubic filter usually provides a slightly better results (can be implemented in real-time) and lanczos filter usually gives best visual results, but is very computationally expensive (usually implemented for down-sampling images during conversion).

The difference within up-scaling is less noticeable, and there is no reliable ways achieving better results than simple Linear filter.
https://en.wikipedia.org/wiki/Image_scaling

Note that everything above is about image filtering - it has nothing to do with row-interleaved stereoscopic output. sView provides straight-forward discard row-interleaved implementation (so that the rows for another eye are just discarded). Some applications implement an alternative row-interleaved output, blending together two nearest rows - this reduces a negative effect of lost pixels by making image blurry. I've played with this filter in iZ3D driver and after some tests decided that it doesn't worth, though some users might found blurry image more preferable.

**Comment by freewee** [comment]
Thank you for the answer!
The problem is not only with row interlaced , I noticed the same with SBS pictures: when the SBS comes from an other soft, and is displayed on my passive LG TV, the result is really better than with sView, that gives  artefacts on oblique lines. I made many tests in order to find a resolution for this problem, without success...
All the pictures I send to my TV are 1080 pixel height, same as my monitor and my TV resolution.
I tested stereoscopic player, stereophoto maker, 3d tv play NVidia, with same typical pictures(oblique lines), and I don' t know why sView can't display as good as the other softs.
This is a png capture I think! It' s difficult to show the problem, but on the bottom of the picture,
![capture du 2018-12-11 18-30-49](https://user-images.githubusercontent.com/19634222/49819774-868a9f00-fd76-11e8-9b14-9a9944043b8e.png)
you can see there is a difference! But there is also a difference on the big piece of wood, when looking with the glasses, but it is not obvious on the capture! The option "anti aliasing" is selected in Stereophoto maker. When I zoom the photo in Stereophoto maker, the picture becomes briefly like the aspect in sView, then becomes smooth.
That 's why I thought there was something wrong or missing in sView???

**Comment by gkv311** [comment]
Could you please also attach the image itself?

**Comment by freewee** [comment]
This is the file.
This example was the last picture I was working on, but I remember the first time I noticed the problem, it was on a picture of a tree, I will try to find it!
I see that mpo is not supported, I will send it to you by mail.

**Comment by gkv311** [comment]
MPO is just a JPEG file; you can rename file extension to .jpg to workaround limitations (although I have not tried attaching images to github).

**Comment by freewee** [comment]
![sculpture jc](https://user-images.githubusercontent.com/19634222/49822958-cf465600-fd7e-11e8-9bb6-d0dd05f5f905.jpeg)

**Comment by gkv311** [comment]
Added "Trilinear" filtering option (disabled by default), which implies generation of texture mip-map levels (downscaled image is better smoothed).

a1af0e0d088ced60ef740bd46bc782952b8e7597

**Comment by gkv311** [comment]
"Smoothing" option has been added to Interlaced Output. This option provides effect similar to "Optimized" option in legacy stereoscopic drivers like iZ3D.

The default interlaced output renders left/right views at native resolution and just discards rows for related views.
This produces a sharp output with spatial information matching physical resolution (e.g. in row interleaved display rows for left and right views do not overlap - they physically displaced).
If display resolution is not good enough, small details like thin lines or tiny text might become difficult to read.

"Smoothing" option renders left/right views at native resolution but while drawing each final row it blends result between displayed and discarded rows (within each view independently).
The result is a more blurred output, but also lesser noise on small/tiny details while moving camera and better readable small 2D text.

The option is currently disabled by default. When I've first seen this option in stereoscopic drivers, I've felt blurry result was less pleasant to me than non-optimized one with sharp details, so I don't know what would most prefer to see by default.

Note that this mode requires additional full-screen draw call, which is negligible on desktop GPUs, but is noticeable on mobile GPUs - so that on old glasses-free devices this option is better to be turned OFF to avoid dropping performance. But on these devices display resolution is usually much higher than on desktop FullHD monitors and interlaced TVs - so I guess this option is less useful there anyway.

**Comment by freewee** [comment]
Hi
Thank you for explanations.
After some tests I confirm that I can watch pictures that were not watchable without this option!
Many thanks!
Only a small thing: When this option is activated, the menu bar is not clear!!
Dominique Breton

**Comment by gkv311** [comment]
> Only a small thing: When this option is activated, the menu bar is not clear!!

Yes, this is expected drawback of this blurring approach. But menu looks fine (readable) in my glasses.
