### ISSUE TITLE
sView 3D L/R order on Rokit Pro 3D inconsistent

### ISSUE THREAD

**Issue by jclement46** [gkv311/sview#62]
sView correctly displays 3D MP4 videos in SBS format, but when displaying my slides I have to set reverse order to have them displayed on axis. 

There is also a problem with the R/L icon in the upper left corner.  The list of options is cut off on the top when the phone is in landscape mode.  The workaround is to rotate the phone, close the list, and reopen it.  The phone has an extra wide display 2160x1080.

There are samples in the link below:
https://1drv.ms/u/s!AgEkZSUlkAcx3H4y-R4pWn52fpn8?e=73SPz4
The video is loading as of this message.

**Comment by gkv311** [comment]
Neither video nor image file has encoded information about stereoscopic format:
http://sview.ru/en/help/input/

MP4 files are expected to define stereo format through SEI tags, MKV files may also define its own tag; as a workaround, one could encode format via file suffix like **-hsbs**.

JPEG and PNG files also has extensions for defining stereoscopic format tag. JPS and PNS are file extensions for identifying side-by-side JPEG/PNG files.

sView follows convention of NVIDIA 3D Driver generating JPS/PNS images in Right/Left order - hence, opening files with reversed order requires overriding the format via:
- Swapping views (for each file).
- Setting **Parallel Pair** as source format instead of **Source**.
- Saving **JPS** metadata to JPEG file via **File Info** dialog in sView (this wouldn't cause JPEG reencoding).
- Renaming file to .jpg and adding suffix like **-sbs**.
- Converting image with swapped pair order.

**Comment by jclement46** [comment]
The problem of incorrect display also happens on the PPT King 7S.  If I view a video I can see it on axis, but if I view a slide I must view it off axis.   The workaround is to reverse the L/R order.  So between videos and slides the ordering of the vertical R/L strips has been reversed.  This problem is apparently with the  autostereo display, as I have not noticed it in the Windows horizontal strip display.  I do not have an autostereo windows monitor to try it there.

**Comment by jclement46** [comment]
This problem also happens on the Commander tablet.

**Comment by jclement46** [comment]
With more investigation I found that this problem happens with the Windows version.  MY JPS slides have R/L reversed.  I think that sView is interpreting JPS as having cross view by default.  As far as I know there is no "standard"specifying either parallel view or cross view for JPS.  All 3D film cameras and viewers use parallel view.  Printed books with 3D photos also use parallel view.  Stereo Photo Maker assumes parallel view for SBS photos.  My LG Thrill phone produces parallel view videos and pictures.  I do not have information on other digital devices as to whether they tend to produce parallel or cross view images.  The standard for JPG 3D has a bit to indicate 3D and another that should be 0 for cross view, but 1 for parallel.  The de facto digital standard would seem to be parallel.  The major consumer 3D camera, Fuji, does not support SBS.

There are many arguments about whether parallel or cross view is "correct", but it seems that most software assumes parallel view for input.  I would say that JPS should assume parallel view, but I can not say which format most 3D fans use to store their images, but I have mostly encountered parallel view images.  This could be solved by having an option as to how JPS will be interpreted.

As to 3D metadata, some programs do use it.  Magix Movie Edit Pro apparently sets a 3D bit for SBS output, but apparently does not set the anamorphic bit.  However it does correctly set the display aspect ratio.  My 1444x1080 MP4 anamorphic 3D with display aspect 4:3 SBS is interpreted by YouTube and Windows correctly, but sView displays it by default in 3D compressed 2X horizontally.  The 4:3 display tag could be used as a clue that it needs to be expanded.  Stereo Photo Maker completely ignores the metadata and indeed trashes the original metadata.

**Comment by jclement46** [comment]
Thank you for the options to set the default mode for JPS.  That fixes my problem.
