### ISSUE TITLE
Windows thumbnails in Explorer for sView defaulted extensions

### ISSUE THREAD

**Issue by jclement46** [gkv311/sview#74]
When sView is assigned as the default program to open for particular file extensions, it sometimes shows the thumbnails in explorer, but sometimes not.  This should be fixed to always display thumbnails.  It is also desirable to display just one image say the left one, rather than both.  The Windows thumbnails are small so that side by side imae display makes them even smaller and harder to see.  Just fixing the display so that thumbnails are shown is the most urgent request.  As I recall it used to display thumbnails, or perhaps did not block the Windows thumbnail display.

**Comment by gkv311** [comment]
Windows generates thumbnails for images and videos by itself. It is known, however, to ignore some files with unknown extension - like JPS or PNS. I would first suggest pushing this feedback to Windows developers. As they Windows 10 receive new features 1-2 times per year, they might listen.

It is possible registering an own thumbnail provider on Windows, although I don't know if it may/should override standard provider for images and videos, as it is expected to be well-optimized for that purpose.

Thumbnail provider is not a standalone application and works differently, so that dedicated development will be required. One problem here is that OpenGL accelerated may be inaccessible, and such process is expected to be executed with low priority and minimal resources utilization. This is problematic to sView, because currently it works in a way, that image should be loaded as whole into memory - which might mean 512 MiB and even more for large images (some image libraries might load a limited portion of image, which allows to perform some operations like generation of down-sampled thumbnail with minimal memory utilization, but this feature is not implemented by FFmpeg used by sView).

**Comment by jclement46** [comment]
This was a mistake on my part, as I was looking at videos, and the video program did not put a thumbnail in the product, so I got a generic thumbnail.  Actually I have a JPS script which is just the JPG script modified slightly to output the thumbnail.  I probably need to investigate if I can modify the thumbnail.  I also have one for MPO, but it is dangerous because it allows changes to the MPO by Windows, and I have not figured out how to modify it to prevent this.  This on my todo list.  Thanks for the reply.
