### ISSUE TITLE
xde: Any plans to add Youtube's cubemap format to 360 viewing in sView?

### ISSUE THREAD

**Issue by ulf458** [gkv311/sview#79]
There is a cubemap option in the 360 window allready but it don’t work with downloaded YouTube videos…
regards
Ulf Brusquini

**Comment by gkv311** [comment]
YouTube has introduced new 360-degrees packing formula called EAC (Equi-Angular Cubemap).
This packing is intended to provide better quality on lower video resolution / bitrate and considers video encoding specifics.

Unfortunately, the new algorithm is declared superficially without any reference sample / implementation, so that implementing such algorithm requires much efforts and guessing. For the moment, I don't know if I'll have a time for this feature in nearest future - external help or appearance of new samples / projects supporting this format (apart from YouTube) might improve situation.

Here are some useful links related to EAC and other projects trying to decode it:
https://youtube-eng.googleblog.com/2017/03/improving-vr-videos.html
https://github.com/google/spatial-media/blob/master/docs/spherical-video-v2-rfc.md
https://github.com/ytdl-org/youtube-dl/issues/15267

**Comment by ulf458** [comment]
Thanks for your kind answer.
There is a standalone player for mac called Tubbler that can play YouTube VR 360 CubeMap links as equirectangular videos 2D and 3D (TB). Don't know if you can get any info from that app?
Here's alink to Tubbler:
https://www.celmaro.com/tubbler/

Regards
Ulf

**Comment by gkv311** [comment]
> There is a standalone player for mac called 

This one seems to be proprietary and it uses official YouTube API, not standalone files.
So, it will unlikely help (though it might be useful taking a look onto YouTube API - don't know what is provides).

**Comment by ulf458** [comment]
Thanks for reply!
I just thought maby there would be some goodies in the code of the Tubbler player that could be implemented in sView? I mean, a way around the problem could be to integrate such option to sView - playing links directly from YouTube?? Problem with Tubbler is it do not show in 3D...and in YouTube player 3D VR videos only play in anaglyph format...but if we could play links from youtube and the 3D is equirectangular TB, then we can use sView's fantastic options to play the videos as we want! :) ? Or am I wrong?
Thanks 
Ulf

**Comment by ulf458** [comment]
Just a small picture showing that Tubbler show and plays the link from YT as equirectangular 3D 360 VR, but is in Cubemap format video if downloaded from YT as a videofile. (It's my own video from my YT channel)
<img width="960" alt="Tubbler vs YT Cubemap" src="https://user-images.githubusercontent.com/61451369/75981063-fa691800-5ee3-11ea-8a4c-1daa9730bf59.png">

**Comment by gkv311** [comment]
Feature has been implemented within #89.

**Comment by ulf458** [comment]
Great news!!
Thanks a lot!!!!

Ulf Brusquini
